### ISSUE TITLE
AttributeError: 'function' object has no attribute 'find'

### ISSUE THREAD

**Issue by nikhilt44** [kcl-ddh/bacalhau#4]
I am getting the following error,

Traceback (most recent call last):
  File "/Users/nikhilthakur/anaconda/envs/dato-env/bin/bacalhau", line 55, in <module>
    main()
  File "/Users/nikhilthakur/anaconda/envs/dato-env/bin/bacalhau", line 39, in main
    tree.compress()
  File "/Users/nikhilthakur/anaconda/envs/dato-env/lib/python2.7/site-packages/bacalhau/topic_tree.py", line 37, in compress
    self._eliminate_child_with_parent_name(n[0])
  File "/Users/nikhilthakur/anaconda/envs/dato-env/lib/python2.7/site-packages/bacalhau/topic_tree.py", line 77, in _eliminate_child_with_parent_name
    p_name = p[:p.find('.')]
AttributeError: 'function' object has no attribute 'find'

**Comment by jmiguelv** [comment]
Could you please provide some more information, please. What were you executing? What are the Python packages and their versions in the virtual environment?
